# Generated by Django 2.2.12 on 2020-08-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='This is the desc', max_length=150),
            preserve_default=False,
        ),
    ]
