# Generated by Django 2.2.12 on 2020-08-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patram', '0003_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='tim',
            new_name='time',
        ),
    ]
