# Generated by Django 2.2.12 on 2020-09-01 03:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patram', '0005_auto_20200831_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
